[Port]  Discounts In Uplink / Скидки В Аплинке
WWhiteDreamProject/wwdpublic pull request #11
Opened 2024-08-22 21:50 UTC by Spatison

# Описание PR

Порт скидок в аплинке.

---

# Изменения

:cl: Spatison
- add: Add discounts in uplink / Добавлены скидки в аплинк

2024-08-23 14:11 UTC, Remuchi requested changes

2024-08-23 14:11 UTC, Remuchi commented on Content.Shared/_White/StoreDiscount/SalesSpecifier.cs
> +    public string SalesCategory { get; private set; } = string.Empty;
Нет нужны указывать строковые название у датафилдов.

2024-08-23 14:11 UTC, Remuchi commented on Content.Shared/Store/StorePresetPrototype.cs
> +    [DataField("sales")]
строковые название датафилдов не нужны

2024-08-23 14:11 UTC, Remuchi commented on Content.Shared/Store/ListingPrototype.cs
> +    [DataField("saleBlacklist")]
строковые названия датафилдов не нужны

2024-08-23 14:11 UTC, Remuchi commented on Content.Server/_White/StoreDiscount/StoreDiscountSystem.cs
> +    private float GetSale(float minMultiplier, float maxMultiplier)
GetDiscount

2024-08-23 14:11 UTC, Remuchi commented on Content.Server/_White/StoreDiscount/StoreDiscountSystem.cs
> +    public void ApplySales(IEnumerable<ListingData> listings, StorePresetPrototype store)
ApplyDiscounts

2024-08-23 14:11 UTC, Remuchi commented on Content.Shared/Store/ListingPrototype.cs
> +    public int SaleAmount;
DiscountValue

2024-08-27 10:55 UTC, Remuchi approved these changes

2024-08-27 10:55 UTC, merged

2024-08-31 06:01 UTC, whateverusername0 commented
@Spatison не против если я скоммунизжу код для другого репозитория? :trollface:

2024-08-31 09:07 UTC, Spatison commented
> @Spatison не против если я скоммунизжу код для другого репозитория? :trollface:

Не против. APGL 💪