mom get the camera
WWhiteDreamProject/wwdpublic pull request #141
Opened 2024-12-06 17:04 UTC by RedFoxIV

# Описание PR
[smoothrot.webm](https://github.com/user-attachments/assets/9220cdad-9437-4bdb-8a80-25ca0b94cc23)

Чтобы выключить в прототипе:
`smoothRotation = false` в `CombatMode`. Дефолт пока что true.

:cl:
- add: В тестовом режиме: персонажи теперь вращаются на все полные, красивые 360°. Ну, кроме спрайтиков. Спрайтики всё ещё двухмерные, с четырьмя направлениями. Зато какие теперь классные фонарики!

2024-12-06 17:49 UTC, Remuchi commented
@RedFoxIV слушай кролика он умный

2024-12-06 17:51 UTC, Spatison requested changes
Добавь код марки // WD EDIT

2024-12-06 17:51 UTC, Remuchi approved these changes

2024-12-06 17:51 UTC, Remuchi commented
а где нахуй мой комментарий

2024-12-06 17:51 UTC, Remuchi commented on Content.Shared/CombatMode/CombatModeComponent.cs
> +        public bool SmoothRotation = true;
я бы сюда вместо bool сунула напрямую угол. Типа `public float RotationSmoothingMargin = 1`

2024-12-06 17:55 UTC, RedFoxIV commented on Content.Shared/CombatMode/CombatModeComponent.cs
> +        public bool SmoothRotation = true;
идея была в том, чтобы была возможность выключить фичу прямо в прототипах, если что-то пойдёт не так

2024-12-06 17:59 UTC, RedFoxIV commented
> @RedFoxIV слушай кролика он умный

>![image](https://github.com/user-attachments/assets/cebe3a3a-b324-48b5-a076-a21d538af9ec)

в следующий раз получится насрать мне на шапку, не переживай

2024-12-06 18:02 UTC, RedFoxIV commented on Content.Shared/MouseRotator/MouseRotatorComponent.cs
> +using System.Numerics;
![image](https://github.com/user-attachments/assets/0532eebf-8fe4-4cfe-8c95-22f3d571ddec)

2024-12-06 18:04 UTC, Remuchi commented on Content.Shared/CombatMode/CombatModeComponent.cs
> +        public bool SmoothRotation = true;
> идея была в том, чтобы была возможность выключить фичу прямо в прототипах, если что-то пойдёт не так
блять ну ладно поухй окроче

2024-12-06 18:04 UTC, Remuchi commented
иди проверяй @Spatison и мержи если все заебись

2024-12-06 19:03 UTC, Spatison approved these changes

2024-12-06 19:03 UTC, merged

2024-12-10 03:14 UTC, trest100 commented
Я твои руки целовал