[NEW] Added toggle to magnetPickupSystem / [FIX] ore processor fix
WWhiteDreamProject/wwdpublic pull request #15
Opened 2024-08-23 19:24 UTC by HellCatten

# [NEW] MagnetPickupSystem ItemToggle added / [FIX] Ore processor fixed

Описание.

[NEW] Добавлен toggle / переключатель для ore bag / сумки для руды. Изначально выключен. 

[FIX] Исправлена ошибка в компонентах ore processor / плавитель руды. Для плавителя есть специальный компонент/система MaterialStorageMagnetPickupSystem. Позволяет плавителю засасывать руду в тайле. Однако из-за отсутствия PlaceableSurfaceComponent сгрузить руду из сумки невозможно. Только в ручную.

Добавление данного компонента исправляет ситуацию.

---

# Медиа

[FIX] 
https://github.com/user-attachments/assets/d82f8aeb-4696-4ec1-a8f0-62f03be9a12e

[NEW]

https://github.com/user-attachments/assets/bf5134e0-efe9-4862-aad0-f242b963115e

<details><summary>Список</summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Изменения

:cl: Hell_Cat
- add: added toggle in ore bag
- fix: Ore processor fixed

2024-08-23 19:26 UTC, PuroSlavKing commented on Resources/Locale/en-US/storage/components/magnet-pickup-component.ftl
> +comp-magnet-pickup-examined-off = the magnet is currently [color=darkred]off[/color].
нам самим типо переводить в голове?

2024-08-23 19:31 UTC, HellCatten commented on Resources/Locale/en-US/storage/components/magnet-pickup-component.ftl
> +comp-magnet-pickup-examined-off = the magnet is currently [color=darkred]off[/color].
> нам самим типо переводить в голове?

Сделал

2024-08-24 07:29 UTC, HellCatten commented
Можно добавить разные приколы к этой фичи.

Как эффект состояния вкл. Изменение спрайта / добавление эффектов.

2024-08-24 08:06 UTC, Spatison requested changes
К строчкам кода изменённым не в папках вайта следует добавлять комментарий.
```suggestion
Одна строчка кода // WD EDIT
```
```suggestion
// WD EDIT START
Три и более строчки 
// WD EDIT END
```
```suggestion
В прототипе # WD EDIT
```

2024-08-24 19:18 UTC, HellCatten commented
> К строчкам кода изменённым не в папках вайта следует добавлять комментарий.
> 
> ```
> Одна строчка кода // WD EDIT
> ```
> 
> ```
> // WD EDIT START
> Три и более строчки 
> // WD EDIT END
> ```
> 
> ```
> В прототипе # WD EDIT
> ```

Done

2024-08-24 19:25 UTC, HellCatten commented
Work in process

2024-08-25 08:49 UTC, Spatison approved these changes

2024-08-27 10:24 UTC, Remuchi commented
Как только закончишь работу - переоткроешь

2024-08-27 10:47 UTC, HellCatten commented
Добавлены спрайты

2024-08-27 10:47 UTC, HellCatten commented
![image](https://github.com/user-attachments/assets/699f6bba-93b9-4f89-bea4-822d27fa8322)

2024-08-27 10:56 UTC, Remuchi commented
Ошибки в линтинге

2024-08-29 10:22 UTC, HellCatten commented
Failed SpawnAndDeleteAllEntitiesInTheSameSpot [19 s]

Не знаю в чем может быть проблема

2024-08-29 10:28 UTC, Spatison commented
> Failed SpawnAndDeleteAllEntitiesInTheSameSpot [19 s]
> 
> Не знаю в чем может быть проблема

Ошибка не связана с твоим ПРом. При повторной запуске чеков скорее всего она сама исправится.

2024-08-30 03:05 UTC, Remuchi requested changes
Так же запушь свои изменения, связанные с работой его вне пояса. Пускай работает и на земле, ничего страшного.

2024-08-30 19:37 UTC, HellCatten commented
Удалил ClotDef check из-за ненадобности. Ore_bag в инвентаре может быть только в 1 слоте - Belt.

В MagnetPickupSystem Добавлен DataField ForcePickup. При помощи него регулируется работа системы.

True: Магнитит все. В руках, на земле.
False: Работает как раньше. Магнитит только на Belt

2024-09-01 08:53 UTC, Remuchi requested changes
ForcePickup не предиктед. Из-за чего при отключении происходит вечная попытка поднять руду.

2024-09-02 09:46 UTC, HellCatten commented
Исправил Predicted через NetworkedComponent и AutoNetworkedField

2024-09-03 10:17 UTC, Remuchi approved these changes

2024-09-03 10:18 UTC, merged