[Feature] Wormhole Anomaly
WWhiteDreamProject/wwdpublic pull request #156
Opened 2024-12-11 23:58 UTC by PuroSlavKing

# Описание PR

Смешная аномалия, которая появляется в большом количестве на станции и устраивает лютый говняк всему экипажу в течении 90 секунд.

<details><summary>Todo лист, если совсем станет делать нехуй</summary>
<p>

- [ ] Соединить аномалии между собой, создавая реальные червоточины, а не рандомный телепорт.
- [ ] Смена положения аномалии - телепортом, каждые 15 секунд.

</p>
</details>

---

# Медиа

<details><summary>Список</summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Изменения

:cl: PuroSlavKing
- add: Added a random event - "Wormhole". Up to 50 anomalies appear on the station, moving the crew far and for a long time. / Добавлен случайный ивент "Червоточина". На станции появляется до 50 аномалий, перемещающих экипаж далеко и надолго.

2024-12-12 07:07 UTC, PuroSlavKing commented on Resources/Prototypes/_White/GameRules/events.yml
> +    reoccurrenceDelay: 50
> _⚠️ Potential issue_
> 
> **Критические проблемы с балансом события.**
> 
> 1. Длительность события (60 секунд) слишком короткая для такого количества червоточин
> 2. Задержка повторения (50 секунд) меньше длительности события (60 секунд)
> 3. Время первого появления (35 секунд) слишком раннее для столь разрушительного события
> 
> ```diff
> -    weight: 8
> -    duration: 60
> -    minimumPlayers: 15
> -    earliestStart: 35
> -    reoccurrenceDelay: 50
> +    weight: 5
> +    duration: 180
> +    minimumPlayers: 20
> +    earliestStart: 600
> +    reoccurrenceDelay: 1200
> ```
> 
> 📝 Committable suggestion

всё это в минутах, а не секундах, вроде.

2024-12-12 08:19 UTC, PuroSlavKing commented
ebal todo

2024-12-13 07:49 UTC, Remuchi commented on Content.Server/StationEvents/Components/RandomSpawnRuleComponent.cs
> +    public int MaxCount = 1;
валидация значений в компонентах не нужна

2024-12-13 07:50 UTC, Remuchi commented on Content.Server/StationEvents/Events/RandomSpawnRule.cs
> +    private static readonly Random RandomGenerator = new Random(); // WWDP
@PuroSlavKing хорошее замечание кстати

2024-12-13 18:15 UTC, Spatison commented
ТуДо будешь доделывать?

2024-12-13 19:23 UTC, PuroSlavKing commented
> ТуДо будешь доделывать? 

Неасилил, кто-нибудь другой сделает, оно впринцепе и так выполняет свою функцию по проникновению туда куда не стоит

2024-12-15 10:53 UTC, Spatison approved these changes

2024-12-17 07:12 UTC, Remuchi requested changes

2024-12-17 07:12 UTC, Remuchi commented on Content.Server/_White/Anomaly/Effects/WormholeAnomalySystem.cs
> +        }
а зачем тебе от шатдаун если ты его не используешь, удали

2024-12-17 07:12 UTC, Remuchi commented on Content.Server/_White/Anomaly/Effects/WormholeAnomalySystem.cs
> +            }
```suggestion
                return;
```

2024-12-17 07:12 UTC, Remuchi commented on Resources/Prototypes/_White/GameRules/events.yml
> +    maxCount: 50
вообще их реально дохуя. Снизь до 20-35

2024-12-17 13:35 UTC, PuroSlavKing commented on Resources/Prototypes/_White/GameRules/events.yml
> +    maxCount: 50
на ТГ их 400, + большая часть тепается в космос

2024-12-22 05:18 UTC, Remuchi approved these changes

2024-12-22 05:19 UTC, merged