added ClothingLimitVision component
WWhiteDreamProject/wwdpublic pull request #16
Opened 2024-08-24 12:49 UTC by Vaaankas

# Описание PR

Добавлен компонент ClothingLimitVision и клиентский компонент VisionLimit
---
Надетая одежда с ClothingLimitVision ограничивает обзор космонавтика до указанного кол-ва тайлов (примерно).

ClothingLimitVision добавлен сварочной маске.

Цветной оверлей и функционал сварочной маски буду добавлять в отдельных ПР.

# Медиа

<details><summary>Список</summary>
<p>

![Example Media Embed](https://i.imgur.com/zbYRNhA.png)

</p>
</details>

---

# Изменения

:cl: vanx
- tweak: Надетая сварочная маска теперь ограничивает радиус обзора

2024-08-24 13:58 UTC, Spatison requested changes

2024-08-24 13:58 UTC, Spatison commented on Content.Client/Content.Client.csproj
> +    <Folder Include="_White\VisionLimit\Overlays\System\" />
```suggestion
    <Folder Include="Spawners\" />
```
Это тут зачем?

2024-08-24 13:58 UTC, Spatison commented on Content.Shared/Content.Shared.csproj
> +    <ProjectReference Include="..\RobustToolbox\Robust.Client\Robust.Client.csproj" />
Этого тут тоже быть не должно

2024-08-24 13:58 UTC, Spatison commented on Content.Shared/Content.Shared.csproj
> +    <Folder Include="_White\VisionLimit\" />
Это тут лишние

2024-08-24 13:58 UTC, Spatison commented on Content.Client/_White/VisionLimit/Systems/VisionLimitSystem.cs
> +        }
```suggestion
        if (_player.LocalEntity == uid)
            _overlayMan.RemoveOverlay(_overlay);
```
Скобочки можно убрать

2024-08-24 13:58 UTC, Spatison commented on Resources/Prototypes/Entities/Clothing/Head/welding.yml
> +    radius: 6
```suggestion
  - type: Mask # WD EDIT
  - type: ClothingLimitVision # WD EDIT
    radius: 6
```

2024-08-26 15:18 UTC, PuroSlavKing commented on Resources/Prototypes/Entities/Clothing/Head/welding.yml
> +    radius: 6
Радиус слишком большой, 3 будет лучше, тк от 3х до 6 не должно быть видно нормально, в этом радиусе должно быть размытие какое-то или затемление

2024-09-08 15:11 UTC, Vaaankas commented
закрыт с позором

2024-09-08 15:11 UTC, closed without merging