[Feature] Supply Pods
WWhiteDreamProject/wwdpublic pull request #162
Opened 2024-12-13 23:45 UTC by PuroSlavKing

# Описание PR

**Literally yaml hero.**

Бинго лист:
- [ ] Добавить немного кода.
- [ ] Добавить совсем чут чут кода.
- [x] Не добавлять кода.

Inspired by https://github.com/Rxup/space-station-14/pull/840

---

# Медиа

<details><summary>Список</summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Изменения

:cl: PuroSlavKing
- add: Добавлены грузовые капсулы. Синдикат раскошелился и доставляет элитные наборы в грузовых капсулах.

2024-12-14 05:20 UTC, Remuchi requested changes
единственный запрос - поменяй названия папок текстур чтобы они соответствовали формату названий папок .rsi
`SupplyPodBluespace.rsi` -> `supply_pod_bluespace.rsi`

2024-12-14 13:07 UTC, Spatison requested changes
Если есть возможность, убери в рандомных припасах синдиката появление новых капсул, а то попадется тебе святая граната и гондола. Капсула гондолы спровоцирует большой бабах

2024-12-14 13:07 UTC, Spatison commented on Resources/Prototypes/_White/Entities/Structures/Storage/SupplyPod/base_supply_pod.yml
> +    capacity: 0
Поменяй capacity на 10

2024-12-14 13:07 UTC, Spatison commented on Resources/Prototypes/_White/Entities/Structures/Storage/SupplyPod/base_supply_pod.yml
> +    location: Грузовая капсула
Не думаю что для капсулы нужен варп поинт

2024-12-14 13:28 UTC, PuroSlavKing commented on Resources/Prototypes/_White/Entities/Structures/Storage/SupplyPod/base_supply_pod.yml
> +    capacity: 0
Капсула слишком имбовая, в ней можно пережить взрыв ядерки

2024-12-14 13:34 UTC, Spatison commented on Resources/Prototypes/_White/Entities/Structures/Storage/SupplyPod/base_supply_pod.yml
> +    capacity: 0
Сделай тогда их не слишком имбовыми

2024-12-14 13:35 UTC, PuroSlavKing commented on Resources/Prototypes/_White/Entities/Structures/Storage/SupplyPod/base_supply_pod.yml
> +    capacity: 0
Тогда груз при падении будет повреждаться, или вовсе взрываться

2024-12-14 13:55 UTC, Spatison commented on Resources/Prototypes/_White/Entities/Structures/Storage/SupplyPod/base_supply_pod.yml
> +    capacity: 0
Так ты поставь ExplosionResistance на 0.1. При обычно взрыве внутри все будет цело, а ядерка все равно пробьет.

2024-12-14 14:23 UTC, Spatison approved these changes
Вроде все отлично, но опционально можно добавить способ разобрать капсулы

2024-12-14 15:02 UTC, PuroSlavKing commented
> Вроде все отлично, но опционально можно добавить способ разобрать капсулы

готово, теперь капсула разбирается на лист стали, при помощи:
- сварка
- - отвёртка
а Гондола и апельсин разбираются на кусок мяса Гондолы и 3 пачки семян апельсина, при помощи:
- кусачки

2024-12-17 10:58 UTC, Remuchi approved these changes

2024-12-17 19:03 UTC, merged