[Port] Resomi
WWhiteDreamProject/wwdpublic pull request #172
Opened 2024-12-18 16:22 UTC by PuroSlavKing

# Описание PR

Taken from:
- https://github.com/space-syndicate/space-station-14-next/pull/27
- https://github.com/space-syndicate/space-station-14-next/pull/116

---

# Медиа

<details><summary>Список</summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Изменения

:cl: pofitlo-Git & PuroSlavKing
- add: Добавлена новая игровая раса - Резоми!

2024-12-22 05:30 UTC, Remuchi requested changes
test fail related to PR. Go fix it.

2024-12-23 11:44 UTC, Spatison commented
Ну после тестов вроде все норма, но нужно переместить новые компоненты в шараде в папки вайта

2024-12-23 17:15 UTC, Spatison approved these changes
Теперь все по местам

2024-12-24 12:52 UTC, Remuchi approved these changes
ОООО ПОХУЙ

2024-12-24 12:52 UTC, merged