Вернул прежнее величие главе персонала №3
WWhiteDreamProject/wwdpublic pull request #184
Opened 2024-12-22 01:48 UTC by DuckierReaper

Убрал решетки там где не надо, вернув недостающие, по итогам голосования  — 26.11.2024 5:15, доступы ( расширенные )

# Описание PR

Добавляет ХоПу доступы, почти, во все углы станции. По итогам голосования  — 26.11.2024 5:15

---

# Изменения

:cl: ДикПикер
- tweak: Расширенные доступы ХоПа возвращены

2024-12-22 01:48 UTC, DuckierReaper commented
3 попытка

2024-12-22 05:16 UTC, Remuchi commented
это не полный список всех доступов для расширенного. Глянь через консоль и добавь остальные

2024-12-22 10:21 UTC, DuckierReaper commented
Добавил недостающие кроме глав (исключение КМ), оружейной, судебных ролей

2024-12-22 23:23 UTC, DuckierReaper commented
> это не полный список всех доступов для расширенного. Глянь через консоль ID карт и добавь остальные

С доступами сделал. Еще вопрос касательно частот его гарнитуры, их тоже возвращать как прежде? Поставить картридж как у капитана

2024-12-23 17:22 UTC, Spatison requested changes

2024-12-23 17:22 UTC, Spatison commented on Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
> +  - Medical
Тут стоит убрать дельтавишный комент и пометить марками # WD EDIT

2024-12-23 17:22 UTC, Spatison commented on Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
> +  - Corpsman
```suggestion
  # WD EDIT  START
  - Quartermaster
  - Mail
  - Paramedic
  - Psychologist
  - Corpsman
  # WD EDIT END
```

2024-12-23 17:22 UTC, Spatison commented on Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
> +  - Chapel
```suggestion
  - Chapel # WD EDIT
```

2024-12-23 17:37 UTC, DuckierReaper commented
Понял, сейчас залью

2024-12-23 18:12 UTC, DuckierReaper commented
Вроде сделал

2024-12-24 09:30 UTC, Spatison approved these changes

2024-12-24 12:08 UTC, Remuchi approved these changes

2024-12-24 12:09 UTC, merged