oh what fun it is to ride a pimped up getaway
WWhiteDreamProject/wwdpublic pull request #191
Opened 2024-12-23 22:33 UTC by RedFoxIV

# Описание PR

![ezgif-2-476d46bcea](https://github.com/user-attachments/assets/0f04b6aa-197a-4c9c-8d9a-7147b9314267)

:cl:
- add: Новогодние гирлянды! В вашем ближайшем крафтменю.

2024-12-25 21:36 UTC, RedFoxIV commented
тесты попердолило

2024-12-25 21:39 UTC, RedFoxIV commented
э, это про UI
это не моё

2024-12-25 21:40 UTC, RedFoxIV commented
>using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow
как оно вообще туда попало

2024-12-25 21:40 UTC, RedFoxIV commented
короче как всегда

2024-12-25 23:24 UTC, RedFoxIV commented
вроде бы всё

2024-12-25 23:25 UTC, RedFoxIV commented
@coderabbitai full review

2024-12-25 23:29 UTC, RedFoxIV commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +    //}
тебе показалось

2024-12-25 23:48 UTC, RedFoxIV commented on Content.Client/_White/Misc/ChristmasLights/ChristmasLightsSystem.cs
> +    }
сделал

2024-12-25 23:50 UTC, RedFoxIV commented on Content.Client/_White/Misc/ChristmasLights/ChristmasLightsSystem.cs
> +    }
я не успел закоммитить изменения
ты как мне в локальную репу залез?

2024-12-25 23:59 UTC, RedFoxIV commented on Content.Client/_White/Misc/ChristmasLights/ChristmasLightsSystem.cs
> +    }
не увиливай, теперь я всё знаю

2024-12-26 00:29 UTC, DuckierReaper commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +    //}
Новогодний подарок

2024-12-26 00:30 UTC, RedFoxIV commented
мерж со сквошем
прошу блять

2024-12-26 09:20 UTC, ILLUZORR commented
@coderabbitai раскоментируй его бэкдор

2024-12-28 09:59 UTC, DVOniksWyvern commented
@RedFoxIV 
удали комментарии бэкдора, йопта, мне перед западными партнёрами стыдно такое мержить

2024-12-28 13:36 UTC, RedFoxIV commented
если не хочешь, чтобы было ещё стыднее - мержь со сквошем, чтобы мои смешные сообщения к коммитам не просочились в репу

2024-12-29 09:24 UTC, Spatison requested changes

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +        }
```suggestion

        if (!TryGetConnected(uid, out var nodes))
            return;

        foreach (var node in nodes)
        {
            var jolly = Comp<ChristmasLightsComponent>(node.Owner);
            jolly.mode = $"emp{(comp.Multicolor ? "_rainbow" : "")}";
            Dirty(node.Owner, jolly);
        }
```

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +                Dirty(jolly.Owner, jolly);
```suggestion
                Dirty(node.Owner, jolly);
```

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +    int GetNextModeIndex(ChristmasLightsComponent comp) // cycles modes as usual, but also handles the -1 case
```suggestion
    private int GetNextModeIndex(ChristmasLightsComponent comp) // cycles modes as usual, but also handles the -1 case
```

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +        if (comp.CurrentModeIndex == -1) return -1;
```suggestion
        if (comp.CurrentModeIndex == -1)
            return -1;

```

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +        EntityUid uid = GetEntity(args.target);
```suggestion

        var uid = GetEntity(args.target);
```

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +        _audio.PlayPredicted(thisComp.ButtonSound, uid, user);
PlayPredicted Не работает на сервер части, он предназначен только для shared

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +        }
```suggestion

        if (HasComp<EmaggedComponent>(uid))
            return;
        
        var jolly = Comp<ChristmasLightsComponent>(uid);
        UpdateAllConnected(uid, jolly.LowPower, GetNextModeIndex(jolly));
```

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +        EntityUid uid = GetEntity(args.target);
```suggestion

        var uid = GetEntity(args.target);
```

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +        _audio.PlayPredicted(thisComp.ButtonSound, uid, user);
PlayPredicted Не работает на сервер части, он предназначен только для shared

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +        }
```suggestion

        if (HasComp<EmaggedComponent>(uid))
            return;
        
        var jolly = Comp<ChristmasLightsComponent>(uid);
        UpdateAllConnected(uid, !jolly.LowPower, GetNextModeIndex(jolly));
```

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +        }
```suggestion
        if (newModeIndex < 0 || !TryGetConnected(uid, out var nodes))
            return;
        
        foreach (var node in nodes)
        {
            var jollyUid = node.Owner;
            if (!TryComp<ChristmasLightsComponent>(jollyUid, out var jolly)
                || HasComp<EmaggedComponent>(jollyUid))
                continue;
            
            jolly.LowPower = brightness;
            jolly.mode = jolly.modes[newModeIndex];
            Dirty(jollyUid, jolly);
        }
```

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Nodes/SamePrototypeAdjacentNode.cs
> +        }
```suggestion
        if (!string.IsNullOrEmpty(OwnerPrototypeID))
            return;
        
        var proto = entMan.GetComponent<MetaDataComponent>(owner).EntityPrototype;
        DebugTools.Assert(proto is not null, "SamePrototypeAdjacentNode used on an entity with no EntityPrototype specified in metadata. Please reconsider your life choices that have lead you to this point.");
        OwnerPrototypeID = proto.ID;
```

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Nodes/SamePrototypeAdjacentNode.cs
> +    public override IEnumerable<Node> GetReachableNodes(TransformComponent xform,
Пропуск перед функцией

2024-12-29 09:24 UTC, Spatison commented on Content.Server/_White/Nodes/SamePrototypeAdjacentNode.cs
> +                spaNode.OwnerPrototypeID == this.OwnerPrototypeID)
```suggestion
                spaNode.OwnerPrototypeID == OwnerPrototypeID)
```

2024-12-29 09:24 UTC, Spatison commented on Resources/Locale/ru-RU/_white/fluff/christmaslights.ftl
> +
Перевод прототипов лучше поместить отдельно в соответствующей папке

2024-12-29 09:24 UTC, Spatison commented on Resources/Prototypes/_White/Entities/Structures/Wallmounts/christmaslights.yml
> +        offset: 0
@RedFoxIV 15 и правда слишком мало, поставь 30

2024-12-29 09:24 UTC, Spatison commented on Resources/Prototypes/_White/Entities/Structures/Wallmounts/christmaslights.yml
Тут стоит добавить suffix к гирляндам с обозначением их цвета

2024-12-29 09:24 UTC, Spatison commented on Resources/Locale/ru-RU/_white/fluff/christmaslights.ftl
> +christmas-lights-unresponsive = Ничего не происходит...
Нужна английская локализация

2024-12-30 18:23 UTC, RedFoxIV commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +                Dirty(jolly.Owner, jolly);
результат одинаковый, но всё равно немножко невалидно:
в Dirty мы отправляем Uid сущности и компонент, который на этой сущности висит.

2024-12-30 18:25 UTC, RedFoxIV commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +        _audio.PlayPredicted(thisComp.ButtonSound, uid, user);
работает, просто я его, наверное, использую немножко не по назначению.
Он отправляет звук всем слушателям кроме user.
Это чтобы шаред на клиенте играл звук сразу, а шаред на сервере отправлял звук всем, кроме клиента, где этот звук уже сыграл

2024-12-30 18:27 UTC, RedFoxIV commented on Content.Server/_White/Nodes/SamePrototypeAdjacentNode.cs
> +        }
это вообще надо исправить нахуй, я изначально OwnerPrototypeID хотел под DataField засунуть, но передумал

2024-12-30 18:28 UTC, RedFoxIV commented on Content.Server/_White/Nodes/SamePrototypeAdjacentNode.cs
> +                spaNode.OwnerPrototypeID == this.OwnerPrototypeID)
это чтобы подчеркнуть, что с чем сравнивается, но в целом согласен, можно убрать

2024-12-30 18:30 UTC, RedFoxIV commented on Content.Shared/_White/Misc/ChristmasLights/SharedChristmasLightsSystem.cs
> +        //args.PushMarkup(_loc.GetString("christmas-lights-examine-toggle-brightness-tip"), 0);
потому что изначально я держал в экзамайне подсказку о том, как управлять гирляндами (клик для режима, альтклик для яркости), но если я их держал только на клиенте, то они через полсекунды пропадали. Сначала вынес в шаред, а потом перенёс функционал на вербы и подсказки стали не нужны.

2024-12-30 18:30 UTC, RedFoxIV commented on Resources/Locale/ru-RU/_white/fluff/christmaslights.ftl
> +christmas-lights-unresponsive = Ничего не происходит...
blyaaaaaaa

2024-12-30 18:32 UTC, RedFoxIV commented on Content.Client/_White/Misc/ChristmasLights/ChristmasLightsSystem.cs
![image](https://github.com/user-attachments/assets/9ddb8c09-a6c4-42dd-93ec-501c2d925d1c)

2024-12-30 18:54 UTC, RedFoxIV commented on Content.Server/_White/Nodes/SamePrototypeAdjacentNode.cs
> +    public override IEnumerable<Node> GetReachableNodes(TransformComponent xform,
+

2024-12-30 18:54 UTC, RedFoxIV commented on Content.Server/_White/Misc/ChristmasLightsSystem.cs
> +
+

2024-12-30 18:54 UTC, RedFoxIV commented on Resources/Prototypes/_White/Entities/Structures/Wallmounts/christmaslights.yml
> +        offset: 0
+

2024-12-31 00:54 UTC, Spatison requested changes

2024-12-31 00:54 UTC, Spatison commented on Content.Client/_White/Misc/ChristmasLights/ChristmasLightsSystem.cs
> +    private bool Cycle(float seconds) => curtime % (seconds * 2) <= seconds;
```suggestion
    private static float Sin(float x) => (float) ((8 * MathF.Sin(x) + MathF.Sin(3 * x)) / 14 + 0.5);
    
    private static float Step(float x, int stepsNum) => MathF.Round(x * stepsNum) / stepsNum;
    
    private static int Round(float x) => (int) MathF.Round(x);
    
    private float curtime => (float) _timing.CurTime.TotalSeconds;
    
    Color GetRainbowColor(float secondsPerCycle, float hueOffset, int steps) => Color.FromHsv(new Vector4(Step((curtime + hueOffset) % secondsPerCycle / secondsPerCycle, steps), 1f, 1f, 1f));
    
    private bool Cycle(float seconds) => curtime % (seconds * 2) <= seconds;
    
```

2024-12-31 00:54 UTC, Spatison commented on Content.Client/_White/Misc/ChristmasLights/ChristmasLightsSystem.cs
> +    }
@RedFoxIV

2024-12-31 00:54 UTC, Spatison commented on Content.Client/_White/Misc/ChristmasLights/ChristmasLightsSystem.cs
> +    void ModeRainbow(SpriteComponent.Layer layer1, SpriteComponent.Layer layer2, ChristmasLightsComponent comp, SpriteComponent sprite)
```suggestion
    }
    
    void ModeRainbow(SpriteComponent.Layer layer1, SpriteComponent.Layer layer2, ChristmasLightsComponent comp, SpriteComponent sprite)
```

2024-12-31 00:54 UTC, Spatison commented on Resources/Locale/ru-RU/_white/fluff/christmaslights.ftl
> +
Еще надо добавить ин suffix

2024-12-31 00:54 UTC, Spatison commented on Content.Client/_White/Misc/ChristmasLights/ChristmasLightsSystem.cs
> +
Че за пропасть

2024-12-31 00:54 UTC, Spatison commented on Content.Client/_White/Misc/ChristmasLights/ChristmasLightsSystem.cs
> +    //}
Закомментированный код лучше удалить

2024-12-31 01:21 UTC, RedFoxIV commented on Content.Client/_White/Misc/ChristmasLights/ChristmasLightsSystem.cs
> +    private bool Cycle(float seconds) => curtime % (seconds * 2) <= seconds;
уэээ ты мне щитсин сломал

2024-12-31 02:38 UTC, Spatison approved these changes
Просто исправь переводы и все

2024-12-31 02:38 UTC, Spatison commented on Resources/Locale/ru-RU/_white/fluff/christmaslights.ftl
> +christmas-lights-examine-name = рождественская гирлянда
Лучше просто сделать перевод BaseChristmasLights, остальные его подсосут из за того что он их родитель

2024-12-31 02:55 UTC, RedFoxIV commented on Resources/Locale/ru-RU/_white/fluff/christmaslights.ftl
> +christmas-lights-examine-name = рождественская гирлянда
проверял, не подсасывают

2024-12-31 04:20 UTC, Spatison commented on Resources/Locale/ru-RU/_white/fluff/christmaslights.ftl
> +christmas-lights-examine-name = рождественская гирлянда
Тогда сделай наблюдательность перевода.
ent-RedBlueChristmasLights = { ent-BaseChristmasLights }
  .desc = { ent-BaseChristmasLights.desc }

2024-12-31 19:10 UTC, RedFoxIV commented on Resources/Locale/ru-RU/_white/fluff/christmaslights.ftl
> +christmas-lights-examine-name = рождественская гирлянда
а в чём смысл, если я и так и так буду всем подтипам отдельно выставлять имя-описание

2025-03-01 19:58 UTC, DVOniksWyvern commented
Уже первого марта, так что НУ ПОДУМАЕМ КОГДА ЗАПУШИТЬ

2025-03-01 22:26 UTC, closed without merging