[Port] Лежание
WWhiteDreamProject/wwdpublic pull request #2
Opened 2024-08-20 14:58 UTC by Spatison

# Описание PR

Совмещения системы лежания ремучи и ЕЕ.

---

# Медиа

<details><summary>Список</summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Изменения

:cl: Spatison
- add: lying down system / Система лежания

2024-08-22 02:37 UTC, Remuchi requested changes

2024-08-22 02:37 UTC, Remuchi commented on Content.Server/Standing/LayingDownSystem.cs
> +        layingDown.AutoGetUp = _cfg.GetClientCVar(args.SenderSession.Channel, WhiteCVars.AutoGetUp);
Это не должно проверяться каждый раз в ивенте отдельном. Вместо этого, изменения в конфиге просто должны менять компонент.

2024-08-22 02:37 UTC, Remuchi commented on Content.Shared/_White/Standing/SharedLayingDownSystem.cs
> +        RaiseNetworkEvent(new ChangeLayingDownEvent());
Можно лечь, будучи вне гравитации. Необходимо зафиксить

2024-08-22 02:37 UTC, Remuchi commented on Content.Shared/_White/Standing/SharedLayingDownSystem.cs
> +            return;
добавь здесь {}

2024-08-22 02:37 UTC, Remuchi commented on Content.Shared/_White/Standing/SharedLayingDownSystem.cs
> +            return false;
добавь здесь {}

2024-08-22 02:37 UTC, Remuchi commented on Content.Shared/_White/Standing/SharedLayingDownSystem.cs
> +            component.CurrentState = StandingState.Lying;
добавь здесь {}

2024-08-22 02:37 UTC, Remuchi commented on Content.Shared/_White/Standing/SharedLayingDownSystem.cs
> +            return;
добавь здесь {}

2024-08-22 02:37 UTC, Remuchi commented on Content.Shared/_White/Standing/SharedLayingDownSystem.cs
> +            return;
{}

2024-08-22 02:37 UTC, Remuchi commented on Content.Shared/_White/Standing/SharedLayingDownSystem.cs
> +
лишняя строка

2024-08-22 02:37 UTC, Remuchi commented on Content.Shared/_White/Standing/SharedLayingDownSystem.cs
> +    private void OnRefreshMovementSpeed(EntityUid uid, LayingDownComponent component, RefreshMovementSpeedModifiersEvent args)
добавь пустую строку

2024-08-22 02:37 UTC, Remuchi commented on Resources/Locale/en-US/_white/escape-menu/options-menu.ftl
> +ui-options-function-look-up = Look up
Я не думаю что ты в этом PR добавлял что-то на присмотреться?

2024-08-22 07:30 UTC, Spatison commented on Content.Server/Standing/LayingDownSystem.cs
> +        layingDown.AutoGetUp = _cfg.GetClientCVar(args.SenderSession.Channel, WhiteCVars.AutoGetUp);
Метод Subs.CVar не позволяет передавать сесию или ентити.

2024-08-23 13:29 UTC, Remuchi approved these changes

2024-08-23 13:30 UTC, merged