Убийство феленидов в прямом эфире
WWhiteDreamProject/wwdpublic pull request #205
Opened 2024-12-25 19:35 UTC by DuckierReaper

# Описание PR

Убирает расу феленидов из меню кастомизации по итогам голосования 24.12.2024

---

# Изменения

:cl:
- remove: Фелениды убраны🎉🎉🎉 по итогам голосования 24.12.2024

2024-12-25 19:36 UTC, PuroSlavKing commented
а резоми вернуть где???

2024-12-25 19:39 UTC, 2011sunbeam commented
У Оникса же свои планы

2024-12-25 21:07 UTC, DuckierReaper commented
> а резоми вернуть где???

Вернусь домой, МОЖЕТ БЫТЬ, сделаю, я феленидов вырезал с телефона с хуевым интернетом в туалете в гостях,

2024-12-25 22:55 UTC, DuckierReaper commented
Я так подумал что мистер глав кодеры сами справятся с тем чтобы ревертнуть убирание резоми из кастомизации

2024-12-25 23:18 UTC, RedFoxIV commented
![image](https://github.com/user-attachments/assets/c242c141-00a1-448b-ba3b-de3802a816c8)

2024-12-25 23:23 UTC, dexpth commented
НЕТ!!! ОТКАЗАНО!!!!! ❌❌❌❌❌ ХАРАМ!!!!!!!

2024-12-25 23:25 UTC, dexpth commented
# убейте этот пр молю 🙏🙏🙏🙏

2024-12-25 23:27 UTC, dexpth requested changes
хмммм, тут примерно реально всё говно, удалите пр быстренько!!!

2024-12-26 00:30 UTC, RedFoxIV commented
мерж со сквошем
прошу блять

2024-12-28 09:52 UTC, DVOniksWyvern commented
Насрал

2024-12-28 09:52 UTC, closed without merging