Киллер фича
WWhiteDreamProject/wwdpublic pull request #209
Opened 2024-12-26 15:12 UTC by RedFoxIV

# Описание PR

Разбор ПРов
Компил Билдов
Запой Скитузов
Шквал Бекдоров
Разъёб Доёбов
Говно Вопросов

2024-12-26 15:22 UTC, PuroSlavKing commented
черепок

2024-12-26 17:09 UTC, RedFoxIV commented
тесты попердолило опять

2025-01-02 13:59 UTC, Remuchi requested changes

2025-01-02 13:59 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/RulonOboevAspect.cs
> +    EntityUid? existing = null;
```suggestion
    private EntityUid? _existing = null;
```

2025-01-02 13:59 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/RulonOboevAspect.cs
> +    }
```suggestion
    }
```

2025-01-02 13:59 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/RulonOboevAspect.cs
> +        _entManager.System<MetaDataSystem>().SetEntityName(entityUid, name, metadata);
should be dependency

2025-01-02 13:59 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/RulonOboevAspect.cs
> +        var minds = _entManager.System<SharedMindSystem>();
should be dependency

2025-01-02 13:59 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/RulonOboevAspect.cs
> +        if (_entManager.TrySystem<IdCardSystem>(out var idCardSystem))
should be dependency

2025-01-02 13:59 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/RulonOboevAspect.cs
> +                if (_entManager.TrySystem<StationRecordsSystem>(out var recordsSystem)
once again

2025-01-02 13:59 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/RulonOboevAspect.cs
> +                    && _entManager.TryGetComponent(idCard, out StationRecordKeyStorageComponent? keyStorage)
```suggestion
                    && TryComp(idCard, out StationRecordKeyStorageComponent? keyStorage)
```

2025-01-02 13:59 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/RulonOboevAspect.cs
> +        if (_entManager.TrySystem<PdaSystem>(out var pdaSystem))
dependency

2025-01-02 13:59 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/RulonOboevAspect.cs
> +            && _entManager.TryGetComponent<ActorComponent>(entityUid, out var actorComp))
```suggestion
        if (TryComp(entityUid, out ActorComponent? actor))
```

2025-01-02 13:59 UTC, Remuchi commented on Content.Server/_White/AspectsSystem/Aspects/RulonOboevAspect.cs
> +            adminSystem.UpdatePlayerList(actorComp.PlayerSession);
dependency

2025-01-02 15:00 UTC, RedFoxIV commented on Content.Server/_White/AspectsSystem/Aspects/RulonOboevAspect.cs
> +    private void OnPlayerSpawnComplete(PlayerSpawnCompleteEvent args)
а хуй знает

2025-03-01 22:26 UTC, closed without merging