NoviGod
WWhiteDreamProject/wwdpublic pull request #210
Opened 2024-12-26 18:38 UTC by Gersoon458

# Описание PR

Нови годъ на станции + починен комод + скафандры у сб теперь нормальные

---

# Изменения

:cl:
- add: New Year's map update/Новогоднее обновление карт
- tweak: Security now has regular hardsuits, not EE ones/У СБ теперь обычные риги, а не ЕЕшные
- tweak: The Christmas tree has a new texture/У Рождественской ёлки новая текстура
- fix: Map bugs fixed/Пофикшены баги карт

2024-12-27 04:32 UTC, Spatison requested changes

2024-12-27 04:32 UTC, Spatison commented on Resources/Prototypes/Recipes/Construction/furniture.yml
> +    sprite: _White/Structures/Furniture/furniture.rsi
```suggestion
    sprite: Structures/Furniture/furniture.rsi
```
По пути уже лежит наш комод, все респрайты объектов лучше хранить там же где и исходный объект

2024-12-27 04:32 UTC, Spatison commented on Resources/Prototypes/Entities/Structures/Furniture/dresser.yml
> +    noRot: True
```suggestion
    sprite: Structures/Furniture/furniture.rsi
    noRot: True # WD EDIT
```

2024-12-27 04:32 UTC, Spatison commented on Resources/Prototypes/Entities/Objects/Decoration/flora.yml
> +      shader: unshaded
```suggestion
    # WD EDIT START
    noRot: true
    sprite: _White/Objects/Decoration/Flora/christmastree.rsi
    layers:
    - state: christmastree
    - state: glow
      shader: unshaded
    # WD EDIT END
```

2024-12-27 04:32 UTC, Spatison commented on Resources/Prototypes/Entities/Objects/Decoration/flora.yml
> +    - state: presents
```suggestion
    # WD EDIT START
    layers:
    - state: christmastree
    - state: glow
      shader: unshaded
    - state: presents
    # WD EDIT END
```

2024-12-27 04:32 UTC, Spatison commented on Resources/Prototypes/Entities/Objects/Decoration/flora.yml
> +  parent: FloraTreeChristmas01
```suggestion
  parent: FloraTreeChristmas01 # WD EDIT
```

2024-12-27 04:32 UTC, Spatison commented on Resources/Textures/_White/Structures/Furniture/furniture.rsi/dresser.png
Наш комод уже лежит в папках игры, не стоит его дублировать

2024-12-27 04:32 UTC, Spatison commented on Resources/Textures/_White/Structures/Furniture/furniture.rsi/meta.json
Вместо создания новой меты, лучше просто в мете комода из основных папках добавить "directions": 4

2024-12-27 10:23 UTC, Gersoon458 commented on Resources/Textures/_White/Structures/Furniture/furniture.rsi/meta.json
Ну вот на счёт комода. Ремучи мне сказала все респрайты пихать в вайтопапку, комод я забыл пихнуть, потому что на тот момент это была уже третья попытка переноса спрайтов (Раскол все дела). Поэтому думаю лучше перенести комод в вайтопапку, а в старую ебануть обычный комод

2024-12-27 10:28 UTC, Spatison commented on Resources/Textures/_White/Structures/Furniture/furniture.rsi/meta.json
Если пихать все в вайтопапки, то при любом апстриме, где будет задействован данный спрайт придется менять пути. Как по мне, легче просто указать в мете авторство.

2024-12-27 10:30 UTC, Gersoon458 commented on Resources/Textures/_White/Structures/Furniture/furniture.rsi/meta.json
Ну, мне сказали что пихать надо в вайтопапку, вот и пихаю. Кого теперь слушать? Я хз

2024-12-27 10:34 UTC, PuroSlavKing commented on Resources/Textures/_White/Structures/Furniture/furniture.rsi/meta.json
> Ну, мне сказали что пихать надо в вайтопапку, вот и пихаю. Кого теперь слушать? Я хз

Я PuroSlavKing, делай что я скажу - респрайты в кор папки, уникальные текстуры в папку _White.

2024-12-29 17:49 UTC, Remuchi approved these changes

2024-12-29 17:50 UTC, Remuchi commented on Resources/Textures/_White/Structures/Furniture/furniture.rsi/meta.json
true

2024-12-30 01:38 UTC, Spatison commented on Resources/Textures/_White/Structures/Furniture/furniture.rsi/meta.json
@Gersoon458 все еще не резолв

2024-12-31 10:49 UTC, Spatison approved these changes

2024-12-31 10:49 UTC, merged