[Feat] Больше переводов
WWhiteDreamProject/wwdpublic pull request #225
Opened 2024-12-30 08:29 UTC by Remuchi

# Описание PR

Переведены непереведенные датасеты, непереведенные вещи в меню персонажа, культ крови (только локали), имена теперь можно делать только на русском

# Изменения

:cl:
- add: Больше переводов

2024-12-30 08:55 UTC, Spatison requested changes

2024-12-30 08:55 UTC, Spatison commented on Resources/Locale/ru-RU/white-dream/cult/items/general.ftl
> +shuttle-curse-shuttle-arrived = Шаттл уже прибыл. Вы уже не можете его отсрочить.
```suggestion
shuttle-curse-shuttle-arrived = Шаттл уже прибыл. Вы не можете его отсрочить.
```

2024-12-30 08:55 UTC, Spatison commented on Resources/Locale/ru-RU/white-dream/cult/shuttle-curse.ftl
> +shuttle-curse-message-4 = Инженер шаттла закричала «СМЕРТЬ - ЭТО ЕЩЕ НЕ КОНЕЦ» и вырвала провода. Электрическая дуга моментально сожгла ее плоть.
```suggestion
shuttle-curse-message-4 = Инженер шаттла закричала «СМЕРТЬ - ЭТО ЕЩЕ НЕ КОНЕЦ» и вырвала провода. Электрическая дуга моментально сожгла его плоть.
```

2024-12-30 08:55 UTC, Spatison commented on Resources/Locale/ru-RU/white-dream/cult/shuttle-curse.ftl
> +shuttle-curse-message-5 = Инженер шаттла была замечена внутри кабины, лихорадочно раскладывающей свои внутренности на полу в виде какой-то руны. Она истекла кровью раньше, чем мы смогли ей помочь.
```suggestion
shuttle-curse-message-5 = Инженер шаттла была замечена внутри кабины, лихорадочно раскладывающей свои внутренности на полу в виде какой-то руны. Он истек кровью раньше, чем мы смогли ему помочь.
```

2024-12-30 08:55 UTC, Spatison commented on Resources/Locale/ru-RU/white-dream/cult/shuttle-curse.ftl
> +shuttle-curse-message-7 = Труп неопознанного работника шаттла был найден изуродованным до неузнаваемости в главном трюме шаттла, причем на месте происшествия обнаружено не менее пяти уникальных источ
```suggestion
shuttle-curse-message-7 = Труп неопознанного работника шаттла был найден изуродованным до неузнаваемости в главном трюме шаттла, на месте происшествия обнаружено не менее пяти уникальных источников крови.
```

2024-12-30 08:57 UTC, Spatison commented
Надо бы еще старые переводы удалить из папки _white

2024-12-30 08:58 UTC, Remuchi commented
только завтра вечером смогу заняться увы

2024-12-30 10:57 UTC, DuckierReaper commented on Resources/Locale/ru-RU/white-dream/cult/shuttle-curse.ftl
> +shuttle-curse-message-5 = Инженер шаттла была замечена внутри кабины, лихорадочно раскладывающей свои внутренности на полу в виде какой-то руны. Она истекла кровью раньше, чем мы смогли ей помочь.
Говно, если не исправлять первоначальное "Инженер шатлла замеченА", так же и в предыдущих

2024-12-30 14:15 UTC, Remuchi commented on Resources/Locale/ru-RU/white-dream/cult/shuttle-curse.ftl
> +shuttle-curse-message-5 = Инженер шаттла была замечена внутри кабины, лихорадочно раскладывающей свои внутренности на полу в виде какой-то руны. Она истекла кровью раньше, чем мы смогли ей помочь.
> Говно, если не исправлять первоначальное "Инженер шатлла замеченА", так же и в предыдущих

уже резольвнуто

2025-03-12 09:36 UTC, DVOniksWyvern commented
тоже ушло в неактивное, потом переводы отдельно перепроверим и перепоправим

2025-03-12 09:36 UTC, closed without merging