Emp Flashlight
WWhiteDreamProject/wwdpublic pull request #5
Opened 2024-08-21 10:04 UTC by HellCatten

# EmpFlashlight added / Добавлен ЭМИ фонарик

Добавляет синди предмет - Эми фонарик (EMP Flashlight). Имеет свойство эми гранаты. При ударе на entity накладывается Эми эффект.

Добавлен в аплинк.

Баланс через прототип.
---

# Медиа

https://github.com/user-attachments/assets/abdc281c-81c0-4488-82ad-59dba609e9be

<details><summary>Список</summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Изменения

:cl: Hell_Cat
- add: Добавлен предмет аплинка - ЭМИ фонарик.

2024-08-21 10:43 UTC, Tryalkash commented
У нас уже есть бесконечный эми имплант. ПР хуйня короче

2024-08-21 11:00 UTC, HellCatten commented
> У нас уже есть бесконечный эми имплант. ПР хуйня короче

Мне сказали - я сделал

2024-08-22 03:16 UTC, Remuchi requested changes

2024-08-22 03:16 UTC, Remuchi commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +public sealed class EmpHitSystem : EntitySystem
EmpOnHitSystem. Название файла туда же

2024-08-22 03:16 UTC, Remuchi commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +    public override void Initialize()
добавь пустую строку между

2024-08-22 03:16 UTC, Remuchi commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +        if (!TryComp<LimitedChargesComponent>(uid, out charges))
нет смысла выносить определение `charges` вне TryComp блока
```suggestion
        if (!TryComp(uid, out LimitedChargesComponent? charges))
```

2024-08-22 03:16 UTC, Remuchi commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +        if (charges != null && args.HitEntities.Count > 0)
Проверка на null тут не нужна. TryComp уже возвращает not-null компонент по определению..

2024-08-22 03:16 UTC, Remuchi commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +using Content.Shared.Charges.Components;
Почисти using. Тут много ненужных

2024-08-22 03:16 UTC, Remuchi commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +    [Dependency] private readonly EntityLookupSystem _lookup = default!;
Зависимость нигде не используется, удали её

2024-08-22 03:16 UTC, Remuchi commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +            _emp.EmpPulse(Transform(affected).MapPosition, comp.Range, comp.EnergyConsumption, comp.DisableDuration);
`Transform(affected).MapPosition` помечен разработчиками как `obsolete`. 
```suggestion

    [Dependency] private readonly SharedTransformSystem _transform = default!;

            _emp.EmpPulse(_transform.GetMapCoordinates(affected), comp.Range, comp.EnergyConsumption, comp.DisableDuration);
```

2024-08-22 03:16 UTC, Remuchi commented on Resources/Prototypes/_White/Entities/Objects/Tools/EmpFlashlight.yml
> +          Blunt: 0
будет смешно ему добавить 12 блант урона. Сделай это

2024-08-22 03:17 UTC, Remuchi commented
Забыла указать. 30 секунд звучит как слишком быстро, с учетом 3 зарядов. Поставь минуту

2024-08-22 06:10 UTC, HellCatten commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +public sealed class EmpHitSystem : EntitySystem
Solved

2024-08-22 06:11 UTC, HellCatten commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +    public override void Initialize()
Solved

2024-08-22 06:11 UTC, HellCatten commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +        if (!TryComp<LimitedChargesComponent>(uid, out charges))
Solved

2024-08-22 06:11 UTC, HellCatten commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +        if (charges != null && args.HitEntities.Count > 0)
Solved

2024-08-22 06:11 UTC, HellCatten commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +using Content.Shared.Charges.Components;
Solved

2024-08-22 06:11 UTC, HellCatten commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +    [Dependency] private readonly EntityLookupSystem _lookup = default!;
Solved

2024-08-22 06:12 UTC, HellCatten commented on Content.Server/_White/EmpFlashlight/EmpHitSystem.cs
> +            _emp.EmpPulse(Transform(affected).MapPosition, comp.Range, comp.EnergyConsumption, comp.DisableDuration);
Solved. Понял

2024-08-22 06:12 UTC, HellCatten commented on Resources/Prototypes/_White/Entities/Objects/Tools/EmpFlashlight.yml
> +          Blunt: 0
Solved

2024-08-23 02:05 UTC, Remuchi approved these changes

2024-08-23 02:53 UTC, merged