[FIX] IPC damage modifier
WWhiteDreamProject/wwdpublic pull request #53
Opened 2024-09-10 09:50 UTC by HellCatten

# [FIX] IPC damage modifier | [FIX] Исправлен модификатор урона у IPC

Описание.

Необходимо настроить модификатор урона, чтобы IPC не получали урон от осколков стекла.

---

# Изменения

- [x] Исправить урон осколком расе IPC
- [ ] Добавить MinDamage в DamageModifierSet.
MinDamage должен блокировать урон, меньше заданного значения. В отличии от FlatReduction, который отнимает урон.

:cl: Hell_Cat
- fix: Исправлен урон осколком по IPC

2024-09-13 07:28 UTC, HellCatten commented
Проверял на фелинидах и лаве. Пока что не работает.

2024-09-13 10:08 UTC, HellCatten commented
@coderabbitai review

2024-09-13 10:10 UTC, HellCatten commented
@coderabbitai full review

2024-09-13 12:40 UTC, HellCatten commented
https://github.com/user-attachments/assets/71ce28da-4bca-4803-90ea-7d5b95feba8d

Works fine

2024-09-13 12:46 UTC, HellCatten commented
LiquidPlasma actually was a lava analog, just with plasma. Fixing it

2024-09-13 13:48 UTC, Remuchi requested changes

2024-09-13 13:48 UTC, Remuchi commented on Content.Shared/StepTrigger/Prototypes/StepTriggerGroup.cs
> +        public List<string>? Types = null;
```suggestion
        [DataField]
        public List<ProtoId<StepTriggerTypePrototype>>? Types = null;
```

2024-09-13 13:48 UTC, Remuchi commented on Content.Shared/StepTrigger/Systems/StepTriggerSystem.cs
> +            }
Это бы по хорошему вынести в отдельный метод. Условно должен быть метод `Validate` у твоей `StepTriggerGroup`, который будет проверять, удовлетворяет ли сущность запросам вайтлиста. Пример у того же `EntityWhitelist` есть.

2024-09-13 19:47 UTC, HellCatten commented on Content.Shared/StepTrigger/Prototypes/StepTriggerGroup.cs
> +        }
Не работает. Я умнее.

2024-09-13 21:14 UTC, Vaaankas commented on Content.Shared/StepTrigger/Prototypes/StepTriggerGroup.cs
> +        }
ахуеть бот сиськи скинул

2024-09-16 14:16 UTC, Remuchi approved these changes

2024-09-16 14:16 UTC, merged