[Port] Log Actions In The Chat / Логирование Действий В Чат
WWhiteDreamProject/wwdpublic pull request #57
Opened 2024-09-14 12:02 UTC by Spatison

# Описание PR

Порт логирование действий в чат.

---

# Изменения

:cl:
- add: Added Logging Of Chat Action / Добавлено Логирование Действий В Чат

2024-09-14 12:39 UTC, HellCatten commented
Нужны скрины из игры

2024-09-15 12:44 UTC, Remuchi requested changes

2024-09-15 12:44 UTC, Remuchi commented on Content.Client/Popups/PopupSystem.cs
> +        private bool _isLogging; // WD EDIT
`_shouldLogInChat`

2024-09-15 12:44 UTC, Remuchi commented on Content.Client/Popups/PopupSystem.cs
> +            };
Это должно быть вынесено в отдельное константное поле, а не определяться каждый раз заново в методе

2024-09-15 16:05 UTC, Remuchi approved these changes

2024-09-15 16:06 UTC, merged