[Port] Experimental Teleporter / Экспериментальный Телепортатор
WWhiteDreamProject/wwdpublic pull request #63
Opened 2024-09-21 10:12 UTC by Spatison

# Описание PR

Порт экспериментального телепорта синдиката

---

# Медиа

[Видео](https://youtu.be/n7scoN1NbHs)

---

# Изменения

:cl: Spatison
- add: Added experimental syndicate teleporter / Добавлен экспериментальный телепортатор синдиката

2024-09-26 02:03 UTC, Remuchi requested changes

2024-09-26 02:03 UTC, Remuchi commented on Content.Server/_White/Teleporter/ExperimentalTeleporterSystem.cs
> +    private void SoundAndEffects(ExperimentalTeleporterComponent component, EntityCoordinates coords, EntityCoordinates oldCoords)
```suggestion
    private void PlaySoundAndEffects(ExperimentalTeleporterComponent component, EntityCoordinates coords, EntityCoordinates oldCoords)
```

2024-09-26 02:03 UTC, Remuchi commented on Content.Server/_White/Teleporter/ExperimentalTeleporterSystem.cs
> +        return Angle.FromDegrees(component.RandomRotations[randomRotation]).RotateVec(offset.Normalized() * length);
@Spatison актуальная заметка.

2024-09-26 02:03 UTC, Remuchi commented on Content.Server/_White/Teleporter/ExperimentalTeleporterSystem.cs
> +            return;
@Spatison актуальная заметка

2024-09-27 02:12 UTC, Remuchi approved these changes

2024-09-27 02:12 UTC, merged

2025-06-17 17:12 UTC, Aineias1 reviewed
.

2025-06-17 17:13 UTC, 89Eblan commented
> .
И зачем?

2025-06-17 17:54 UTC, pheenty commented
Чтобы ты спросил