Translation/Перевод
WWhiteDreamProject/wwdpublic pull request #69
Opened 2024-09-26 18:36 UTC by Blackcat-loroved

Перевод некоторых предметов

# Описание PR

Описание.

---

# Медиа

<details><summary>Список</summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Изменения

:cl:
- add: Добавлено веселье :D
- tweak: Изменено веселье~
- fix: Исправлено веселье!
- remove: Удалено веселье :(

2024-09-27 02:06 UTC, Remuchi requested changes

2024-09-27 02:08 UTC, Remuchi commented on Resources/Locale/ru-RU/entities/objects/devices/door_remote.ftl
> +
```suggestion

```

2024-09-30 13:12 UTC, Remuchi requested changes

2024-09-30 13:12 UTC, Remuchi commented on Resources/Locale/ru-RU/entities/objects/weapons/guns/battery/battery_guns.ftl
> +    .desc = Это дорогая современная реконструкция старинного энергетического пистолета. Пистолет имеет два режима стрельбы, но у него отсутствует микроядерная батарея. Сделан по образу и подобию анти
Так `реконструкция старинного энергетического пистолета` или `Сделан по образу и подобию антикварного энергетического пистолета.`?

2024-09-30 13:12 UTC, Remuchi commented on Resources/Locale/ru-RU/entities/objects/weapons/guns/shotguns/shotguns.ftl
> +    .desc = Дробовик "Адъютант" продаваемый как оружие против беспорядкой. Специальная система отвода газов даёт возможность вести подавляющий огонь. Использовался для подавления мятежей во многих си
```suggestion
    .desc = Дробовик "Адъютант" продается как оружие против беспорядкой. Специальная система отвода газов даёт возможность вести подавляющий огонь. Использовался для подавления мятежей во многих системах.
```

2024-09-30 13:12 UTC, Remuchi commented on Resources/Locale/ru-RU/entities/structures/shuttles/cannons.ftl
> +    .desc = Небольшой стационарный гранатомет, вмещающий 2 гранаты. Чаще всего используется небольшими рейдерскими кораблями. Несмотря на название, не выглядит слишком уж дружелюбно.
Повтор одного и того же слова в двух подряд идущих предложениях выглядит криво.
```suggestion
    .desc = Небольшой стационарный гранатомет, вмещающий 2 гранаты. Чаще всего используется рейдерскими кораблями. Несмотря на название, не выглядит слишком уж дружелюбно.
```

2024-09-30 13:12 UTC, Remuchi commented on Resources/Locale/ru-RU/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Новая Кукурузицца! Кукурузная пицца с корочкой из кукурузных початков, которая заставит вас сказать "почему это существует?". По непонятным причинам в составе присутсвтует цезий.
```suggestion
    .desc = Новая Кукурузицца! Кукурузная пицца с корочкой из кукурузных початков, которая заставит вас сказать "почему это существует?". По непонятным причинам в составе присутствует цезий.
```

2024-09-30 13:12 UTC, Remuchi commented on Resources/Locale/ru-RU/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Из всех станций в юрисдикции НьяноТрасена «Блюдце» получило рейтинг №1 из 5! Поздравляем!
```suggestion
    .desc = Из всех станций в юрисдикции НаноТразен «Блюдце» получило рейтинг №1 из 5! Поздравляем!
```

2024-10-11 04:21 UTC, Remuchi approved these changes

2024-10-11 04:25 UTC, Remuchi requested changes

2024-10-11 04:25 UTC, Remuchi commented on Resources/Locale/ru-RU/entities/objects/weapons/guns/ammunition/boxes/special.ftl
> +    .desc =
а где описания то ну емае

2024-10-11 15:38 UTC, Blackcat-loroved commented on Resources/Locale/ru-RU/entities/objects/weapons/guns/ammunition/boxes/special.ftl
> +    .desc =
У других патронов, гильз, коробок с патронами и спидлоадеров описания я не увидел

2024-11-14 09:48 UTC, DVOniksWyvern commented
Блэккэт самоуничтожился. 

@Remuchi Закрываю ПР или кто-то подберёт думаешь?

2024-11-15 09:27 UTC, Blackcat-loroved commented
> Блэккэт самоуничтожился.
> 
> @Remuchi Закрываю ПР или кто-то подберёт думаешь?

Бу испугался не бойся я друг я тебя не обижу иди сюда иди ко мне сядь рядом со мной посмотри мне в глаза ты видишь меня я тоже тебя вижу давай смотреть друг другу в глаза пока наши глаза не вытекут что ты не хочешь почему что-то не так

2024-11-15 09:30 UTC, Blackcat-loroved commented
Простите, что 13-летнее дитё отняло у вас время, а потом сдетонировало. Можете токи спросить что почему и как если интересно

2024-11-29 03:54 UTC, closed without merging