[Port] Telescope System / Система Прицеливания
WWhiteDreamProject/wwdpublic pull request #8
Opened 2024-08-21 19:27 UTC by Spatison

# Описание PR

Порт системы прицеливания.

---

# Медиа

<details><summary>Список</summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Изменения

:cl: Spatison
- add: Telescope System / Система Прицеливания
- tweak: Now you can aim from Hristov / Теперь можно прицеливаться из Христова

2024-08-22 02:17 UTC, Remuchi requested changes

2024-08-22 02:17 UTC, Remuchi commented on Content.Shared/_White/Telescope/SharedTelescopeSystem.cs
> +            telescope = entityTelescope;
здесь желательно взять в {} блоки внутри. Условие if слишком большое.

2024-08-22 02:17 UTC, Remuchi commented on Content.Shared/_White/Telescope/SharedTelescopeSystem.cs
> +    }
этот метод нигде не используется, не думаю, что он нужен особо.

2024-08-22 02:17 UTC, Remuchi commented on Content.Shared/_White/Telescope/SharedTelescopeSystem.cs
> +            _eye.SetOffset(ent, offset, ent);
Добавь сюда {}

2024-08-22 09:55 UTC, Spatison commented on Content.Shared/_White/Telescope/SharedTelescopeSystem.cs
> +    }
Этот метод нужен для аспекта

2024-08-23 01:45 UTC, Remuchi approved these changes

2024-08-23 01:45 UTC, merged